### ISSUE TITLE
来提个issue支持一下: Descirption 拼写错误

### ISSUE THREAD

**Issue by Aleksanaa** [jmxl/MonitorInfo#1]
色域是gamut，不是gaumt

![滑稽.gif](https://s1.ax1x.com/2020/03/19/8ySmbF.gif)

**Comment by jmxl** [comment]
已更正描述



> 色域是gamut，不是gaumt
> 
> ![滑稽.gif](https://camo.githubusercontent.com/dbf7a015a0c768ed5c1baa6f39760ef0907d12b8/68747470733a2f2f73312e617831782e636f6d2f323032302f30332f31392f3879536d62462e676966)
